### PR TITLE
Use IIFE & reflect NPM availibility

### PR DESCRIPTION
**Pull request by killzoner**
Hi,

This pull request suggests to use IIFE to avoid name collision between possible global function (ie find/findIndex/etc.) and actually relfect in the home page that the package is available on NPM.

I'm suggesting this pull request here and not in the main/original repo since I see no activity for a long time and i need NPM distro anyway.

### CODE REVIEW

**Comment by pkempenaers** [comment]
I've recently become the maintainer of the main repo so I'll merge it in there, I simply have a rather large backlog atm.

**Comment by killzoner** [comment]
Ok, good news then! Thanks for the work, tell me if i can help

**Comment by pkempenaers** [comment]
Could you create the same PR over there? (and rebase if needed) That'll make it simple for me to merge it in

**Comment by killzoner** [comment]
No problem i'll take care of it today

**Comment by killzoner** [comment]
Why do you mean by "over there"? The main repo?

**Pull request closed without merging**
